spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/demoDB
    username: usr
    password: pwd
  flyway:
    enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
server:
  port: 8081
logging:
  level:
    log4j.category.org.springframework.jdbc.core : TRACE
minio:
  url: http://localhost:9001
  key: AKIAIOSFODNN7EXAMPLE
  secretkey: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
  bucketname: docs